version: "3"
services:
  docker-test:
    stdin_open: true
    tty: true
    build: .
    ports: 
    - "3000:3000"
    volumes:
    - "./src:/app/src"
    environment:
    - REACT_APP_NAME=react_flow
    - WATCHPACK_POLLING=true
